"""v2.0.0 initial schema

Revision ID: 067deedab1d9
Revises: 
Create Date: 2026-08-04 16:09:03.164844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067deedab1d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'users' in inspector.get_table_names():
        print("[Alembic] Tables already exist! Skipping initial migration to prevent crash.")
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('oauth_provider', sa.String(length=20), nullable=True),
    sa.Column('oauth_id', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active_acc', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scan', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backup_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_backup', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_days', sa.Integer(), nullable=True),
    sa.Column('backup_location', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('login_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('drive_path', sa.String(length=16), nullable=False),
    sa.Column('drive_model', sa.String(length=128), nullable=True),
    sa.Column('drive_serial', sa.String(length=64), nullable=True),
    sa.Column('drive_type', sa.String(length=8), nullable=True),
    sa.Column('drive_firmware', sa.String(length=32), nullable=True),
    sa.Column('capacity_bytes', sa.BigInteger(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=8), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('power_on_hours', sa.Integer(), nullable=True),
    sa.Column('smart_data', sa.Text(), nullable=True),
    sa.Column('benchmark_data', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('ram_percent', sa.Float(), nullable=True),
    sa.Column('disk_read_mb', sa.Float(), nullable=True),
    sa.Column('disk_write_mb', sa.Float(), nullable=True),
    sa.Column('net_sent_mb', sa.Float(), nullable=True),
    sa.Column('net_recv_mb', sa.Float(), nullable=True),
    sa.Column('gpu_percent', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_snapshots_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_snapshots_timestamp'))

    op.drop_table('system_snapshots')
    op.drop_table('scan_results')
    op.drop_table('password_reset_tokens')
    op.drop_table('login_events')
    op.drop_table('backup_records')
    op.drop_table('alerts')
    op.drop_table('users')
    # ### end Alembic commands ###
