"""Initial Schema

Revision ID: b8fff3dbd934
Revises: 
Create Date: 2026-07-28 08:41:33.130686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8fff3dbd934'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('oauth_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_active_acc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_scan', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('settings', sa.Text(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=254),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_provider_account'), type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('first_login')
        batch_op.drop_column('provider_id')
        batch_op.drop_column('provider')
        batch_op.drop_column('login_count')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('login_count', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('provider', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('provider_id', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('first_login', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_provider_account'), ['provider', 'provider_id'])
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=254),
               nullable=True)
        batch_op.drop_column('settings')
        batch_op.drop_column('last_scan')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active_acc')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('role')
        batch_op.drop_column('oauth_id')
        batch_op.drop_column('oauth_provider')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    op.create_table('login_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=20), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=512), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
